apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v1-25
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      version: v1-25
  template:
    metadata:
      labels:
        app: nginx
        version: v1-25
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
