apiVersion: v1
kind: Service
metadata:
  name: nginx-service-v1-25
spec:
  selector:
    app: nginx
    version: v1-25
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
